<?
  $this->Load_Class('/Object');
  $this->Load_Trait('/UnitTest/Asserts');
  
  Class C_UnitTest_Context Extends C_Object
  {
    Var $Argumets_ValueByType=[];
    Var $Argumets_ValueByName=[];
    Var $ExpectException;
    Var $IsFailed=False;
    
    Function Register_Argument_Type_Value($Value, $Type=Null)
    {
      $Type??=Get_Class($Value);
      $this->Argumets_ValueByType[$Type]=$Value;
    }
    
    Function Register_Argument_Name_Value($Arg_Name, $Value)
    {
      $this->Argumets_ValueByName[$Arg_Name]=$Value;
    }
    
    Function SetFailed($v=True) { $this->IsFailed=$v; }
    
    Function ExpectException($Exception) { $this->ExpectException=$Exception; }
    
    Function RunTest($Object)
    {
      $Class=New ReflectionClass($Object);
      $this->Log('Log', 'Test ', $Class->GetName());

      $ValueByType=$this->Argumets_ValueByType;
      $ValueByName=$this->Argumets_ValueByName;
      
      ForEach($Class->GetMethods() As $Method)
      {
        If($Method->GetDeclaringClass()->GetName()!==$Class->GetName()) Continue; //TODO: AllowClasses
        If( $Method->IsAbstract    ()) Continue;
      //If( $Method->IsPrivate     ()) Continue;
      //If( $Method->IsProtected   ()) Continue;
      //If(!$Method->IsPublic      ()) Continue;
      //If(!$Method->IsStatic      ()) Continue;
      //If(!$Method->IsUserDefined ()) Continue;
      //$Method->SetAccessable(true);
        $Method_Name=$Method->GetShortName();
      //$this->Log('Debug', 'Test Method ', $Method_Name);
        If(!Str_Starts_With($Method_Name, 'Test')) Continue;
        $Prameters=$Method->GetParameters();
        $Args=[];
        ForEach($Prameters As $Prameter)
        {
          $Arg_Name=$Prameter->GetName();
          If(Array_Key_Exists($Arg_Name, $ValueByName))
          {
            $Args[]=$ValueByName[$Arg_Name];
            Continue;
          }
          $Type=(String)$Prameter->GetType();
          If(Array_Key_Exists($Type, $ValueByType))
          {
            $Args[]=$ValueByType[$Type];
            Continue;
          }
          $this->Log('Error', 'Not found value for ',
            $Type?: 'Any', ' ',$Arg_Name, 
            ' in Method ',$Method_Name, 
            ' Types: ', Array_Keys($ValueByType), 
            ' Names: ', Array_Keys($ValueByName),
          );
          $Args=False;
          Break;
          
        }
        If($Args===False)
          Continue;
        $OldExpectException=$this->ExpectException;
        Try
        {
          $this->IsFailed=False;
          $Ok=False;
          $Method->InvokeArgs($Object, $Args);
          If(!$this->ExpectException)
            $Ok=!$this->IsFailed;
        }
        Catch(Throwable $e)
        {
          If($this->ExpectException &&($e InstanceOf $this->ExpectException))
            $Ok=!$this->IsFailed;
          Else
            $this->Log('Error', 'TestCase chatched an exception:')->Exception($e);
        }
        $this->ExpectException=$OldExpectException;

        $this->Log('Log', '  ', $Method->GetName(), ' ', $Ok? 'Ok':'Error');
      }
    }
  }
?>